DROP TABLE IF EXISTS gear;
DROP TABLE IF EXISTS current_gear;
DROP TABLE IF EXISTS quest_complete;
DROP TABLE IF EXISTS render;
DROP TABLE IF EXISTS ding;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS quest;
DROP TABLE IF EXISTS persona;
