DROP TABLE IF EXISTS gear;
DROP TABLE IF EXISTS current_gear;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS render;
DROP TABLE IF EXISTS ding;
DROP TABLE IF EXISTS quest;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS persona;
